import fs from 'node:fs';
import assert from 'node:assert/strict';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,Contract,id,parseEther,ZeroAddress,ZeroHash} from 'ethers';
const g=ganache.provider({wallet:{totalAccounts:6},chain:{chainId:31337,hardfork:'shanghai'},logging:{quiet:true}});
const p=new BrowserProvider(g,undefined,{cacheTimeout:-1});p.pollingInterval=20;
const users=await Promise.all([0,1,2,3].map(i=>p.getSigner(i))),addresses=await Promise.all(users.map(s=>s.getAddress()));
const artifact=JSON.parse(fs.readFileSync('artifacts/InvoiceLedger.json'));
const ledger=await new ContractFactory(artifact.abi,artifact.bytecode,users[0]).deploy();await ledger.waitForDeployment();
const results=[],gas={deployment:Number((await ledger.deploymentTransaction().wait()).gasUsed)};
async function check(name,fn){try{await fn();results.push({name,passed:true});console.log(`PASS ${name}`);}catch(e){results.push({name,passed:false,error:e.message});console.error(`FAIL ${name}: ${e.message}`);}}
async function rejected(promise,name){let err;try{await promise;}catch(e){err=e;}assert.ok(err,'Expected rejection');const revert=err.revert?.name;if(name)assert.equal(revert,name);}
const due=()=>Math.floor(Date.now()/1000)+1000000;
const amount=parseEther('0.01'),ref=id('INV-001'),doc=id('document');
const invoice=await ledger.invoiceId(addresses[0],ref);
await check('Deployment assigns administrator and zero liability',async()=>{assert.equal(await ledger.administrator(),addresses[0]);assert.equal(await ledger.totalLiability(),0n);});
await check('Create invoice stores exact immutable fields and emits event',async()=>{const r=await(await ledger.createInvoice(ref,addresses[1],amount,due(),doc)).wait();gas.createInvoice=Number(r.gasUsed);assert.equal((await ledger.getInvoice(invoice)).amount,amount);assert.equal((await ledger.getInvoice(invoice)).status,1n);assert.ok(r.logs.some(l=>ledger.interface.parseLog(l)?.name==='InvoiceCreated'));});
await check('Duplicate merchant reference rejected',()=>rejected(ledger.createInvoice.staticCall(ref,addresses[1],amount,due(),doc),'DuplicateInvoice'));
await check('Same reference permitted for a different merchant',async()=>{await(await ledger.connect(users[2]).createInvoice(ref,addresses[1],amount,due(),doc)).wait();assert.notEqual(await ledger.invoiceId(addresses[2],ref),invoice);});
await check('Zero payer rejected',()=>rejected(ledger.createInvoice.staticCall(id('ZERO'),ZeroAddress,amount,due(),doc),'InvalidInvoice'));
await check('Self payment rejected at creation',()=>rejected(ledger.createInvoice.staticCall(id('SELF'),addresses[0],amount,due(),doc),'InvalidInvoice'));
await check('Zero amount rejected',()=>rejected(ledger.createInvoice.staticCall(id('AMOUNT'),addresses[1],0,due(),doc),'InvalidInvoice'));
await check('Past due date rejected',()=>rejected(ledger.createInvoice.staticCall(id('DATE'),addresses[1],amount,1,doc),'InvalidInvoice'));
await check('Empty reference hash rejected',()=>rejected(ledger.createInvoice.staticCall(ZeroHash,addresses[1],amount,due(),doc),'InvalidInvoice'));
await check('Empty document hash rejected',()=>rejected(ledger.createInvoice.staticCall(id('HASH'),addresses[1],amount,due(),ZeroHash),'InvalidInvoice'));
await check('Unspecified payer cannot pay',()=>rejected(ledger.connect(users[2]).payInvoice.staticCall(invoice,{value:amount}),'Unauthorized'));
await check('Underpayment rejected',()=>rejected(ledger.connect(users[1]).payInvoice.staticCall(invoice,{value:amount-1n}),'IncorrectPayment'));
await check('Overpayment rejected',()=>rejected(ledger.connect(users[1]).payInvoice.staticCall(invoice,{value:amount+1n}),'IncorrectPayment'));
await check('Actual reverted payment receipt cannot alter state or credit',async()=>{let reverted=false;try{await(await ledger.connect(users[1]).payInvoice(invoice,{value:amount-1n,gasLimit:200000})).wait();}catch(e){reverted=e.receipt?.status===0;}assert.ok(reverted);assert.equal((await ledger.getInvoice(invoice)).status,1n);assert.equal(await ledger.credits(addresses[0]),0n);});
await check('Exact payment credits merchant and records actual ETH',async()=>{const r=await(await ledger.connect(users[1]).payInvoice(invoice,{value:amount})).wait();gas.payInvoice=Number(r.gasUsed);assert.equal((await ledger.getInvoice(invoice)).status,2n);assert.equal(await ledger.credits(addresses[0]),amount);assert.equal(await ledger.totalLiability(),amount);assert.equal(await p.getBalance(await ledger.getAddress()),amount);});
await check('Duplicate payment rejected',()=>rejected(ledger.connect(users[1]).payInvoice.staticCall(invoice,{value:amount}),'InvoiceNotOpen'));
await check('Paid invoice cannot be cancelled',()=>rejected(ledger.cancelInvoice.staticCall(invoice),'InvoiceNotOpen'));
await check('Administrator cannot withdraw another merchant credit',async()=>{await rejected(ledger.connect(users[3]).withdraw.staticCall(),'NothingToWithdraw');});
await check('Pause requires administrator',()=>rejected(ledger.connect(users[1]).setPaused.staticCall(true),'Unauthorized'));
await check('Pause blocks invoice creation and payments',async()=>{await(await ledger.setPaused(true)).wait();await rejected(ledger.createInvoice.staticCall(id('PAUSED'),addresses[1],amount,due(),doc),'PaymentsPaused');await rejected(ledger.connect(users[1]).payInvoice.staticCall(await ledger.invoiceId(addresses[2],ref),{value:amount}),'PaymentsPaused');});
await check('Withdraw works while paused and clears liability',async()=>{const r=await(await ledger.withdraw()).wait();gas.withdraw=Number(r.gasUsed);assert.equal(await ledger.credits(addresses[0]),0n);assert.equal(await ledger.totalLiability(),0n);assert.equal(await p.getBalance(await ledger.getAddress()),0n);await(await ledger.setPaused(false)).wait();});
await check('Repeat withdrawal rejected',()=>rejected(ledger.withdraw.staticCall(),'NothingToWithdraw'));
const cancelled=await ledger.invoiceId(addresses[0],id('CANCEL'));
await(await ledger.createInvoice(id('CANCEL'),addresses[1],amount,due(),doc)).wait();
await check('Only issuing merchant can cancel',()=>rejected(ledger.connect(users[1]).cancelInvoice.staticCall(cancelled),'Unauthorized'));
await check('Cancellation prevents subsequent payment',async()=>{await(await ledger.cancelInvoice(cancelled)).wait();await rejected(ledger.connect(users[1]).payInvoice.staticCall(cancelled,{value:amount}),'InvoiceNotOpen');});
await check('Unknown invoice payment rejected',()=>rejected(ledger.connect(users[1]).payInvoice.staticCall(id('MISSING'),{value:amount}),'InvoiceNotOpen'));
await check('Expired invoice payment rejected at blockchain time',async()=>{const now=Number((await p.getBlock('latest')).timestamp);const r=id('EXPIRED');await(await ledger.createInvoice(r,addresses[1],amount,now+30,doc)).wait();await g.request({method:'evm_increaseTime',params:[31]});await g.request({method:'evm_mine',params:[]});await rejected(ledger.connect(users[1]).payInvoice.staticCall(await ledger.invoiceId(addresses[0],r),{value:amount}),'InvoiceExpired');});
const fixture=JSON.parse(fs.readFileSync('artifacts/TestMerchant.json'));
const receiver=await new ContractFactory(fixture.abi,fixture.bytecode,users[0]).deploy(await ledger.getAddress());await receiver.waitForDeployment();
const receiverAddress=await receiver.getAddress();
await(await receiver.create(id('RECEIVER'),addresses[1],amount,due(),doc)).wait();
await(await ledger.connect(users[1]).payInvoice(await ledger.invoiceId(receiverAddress,id('RECEIVER')),{value:amount})).wait();
await check('Rejected withdrawal preserves credit and liability atomically',async()=>{await(await receiver.configure(true,false)).wait();let err=false;try{await(await receiver.withdraw({gasLimit:250000})).wait();}catch(e){err=e.receipt?.status===0;}assert.ok(err);assert.equal(await ledger.credits(receiverAddress),amount);assert.equal(await ledger.totalLiability(),amount);});
await check('Reentrant receiver cannot double withdraw',async()=>{await(await receiver.configure(false,true)).wait();await(await receiver.withdraw()).wait();assert.equal(await receiver.reentryBlocked(),true);assert.equal(await ledger.credits(receiverAddress),0n);assert.equal(await ledger.totalLiability(),0n);});
await check('Liability invariant across 12 deterministic multi-merchant payments',async()=>{let total=0n;const credits=new Map();for(let j=0;j<12;j++){const m=j%2===0?0:2;const value=BigInt(j+1)*1000000000000n;const r=id(`PROPERTY-${j}`);await(await ledger.connect(users[m]).createInvoice(r,addresses[1],value,due(),doc)).wait();await(await ledger.connect(users[1]).payInvoice(await ledger.invoiceId(addresses[m],r),{value})).wait();total+=value;credits.set(addresses[m],(credits.get(addresses[m])||0n)+value);assert.equal(await ledger.totalLiability(),total);assert.equal(await p.getBalance(await ledger.getAddress()),total);for(const [a,c]of credits)assert.equal(await ledger.credits(a),c);}for(const m of[0,2])await(await ledger.connect(users[m]).withdraw()).wait();assert.equal(await ledger.totalLiability(),0n);});
const output={environment:'Isolated Ganache local EVM, chain 31337; no Sepolia deployment implied',compiler:'0.8.26',timestamp:new Date().toISOString(),passed:results.filter(r=>r.passed).length,total:results.length,gas,tests:results};
fs.mkdirSync('evidence',{recursive:true});fs.writeFileSync('evidence/contract-tests.json',JSON.stringify(output,null,2));
await g.disconnect();if(output.passed!==output.total)process.exitCode=1;
console.log(`${output.passed}/${output.total} tests passed. Gas: ${JSON.stringify(gas)}`);
